### ISSUE TITLE
Add support for transparent alacritty

### ISSUE THREAD

**Issue by k2662** [const-void/rose-pine-man#1]
![image](https://github.com/user-attachments/assets/d6c3a846-f547-4ffe-9bff-14278f1cd78c)

**Very ugly**

**Comment by const-void** [comment]
Agree, no good!  Will look.  MAN_THEME_BG  / BG2 is the likely culprit.

**Comment by const-void** [comment]
`colorize_man` now accepts an optional second parameter, `transparent`.  Give it a shot! 

Update to latest:
```zsh
$ cd ~/.config/zsh/rose-pine-man
$ git pull
```

Then, in your `~/.zshrc` or wherever, after sourcing, invoke `colorize_man` with your theme of choice and `transparent`:
```zsh
 source ~/.config/zsh/rose-pine-man/rose-pine-man.zsh
 colorize_man rose-pine-moon transparent
```
